Add missing methods from the latest RoleManager interface
casbin/okta-role-manager pull request #2
Opened 2022-11-01 16:54 UTC by checkaayush

## Changes

- Converts the repo into a go module
- Partial upgrade to github.com/casbin/casbin/v2
- Add missing methods to comply with latest RoleManager interface

2022-11-01 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/okta-role-manager?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/okta-role-manager?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/okta-role-manager?pullRequest=2) it.</sub>

2022-11-02 01:15 UTC, hsluoyz requested changes

2022-11-02 01:15 UTC, hsluoyz commented on go.mod
> +	github.com/casbin/casbin v1.9.1
Remove casbin v1.9.1

2022-11-02 01:15 UTC, hsluoyz commented on go.sum
> +github.com/casbin/casbin v1.9.1 h1:ucjbS5zTrmSLtH4XogqOG920Poe6QatdXtz1FEbApeM=
Remove casbin v1.9.1

2022-11-02 04:46 UTC, checkaayush commented on go.sum
> +github.com/casbin/casbin v1.9.1 h1:ucjbS5zTrmSLtH4XogqOG920Poe6QatdXtz1FEbApeM=
Done.

2022-11-02 04:46 UTC, checkaayush commented on go.mod
> +	github.com/casbin/casbin v1.9.1
Done.

2022-11-03 01:17 UTC, hsluoyz approved these changes

2022-11-03 01:20 UTC, merged